name: Deploy MERN app to DigitalOcean

on:
  push:
    branches:
      - ctb-server # The branch to trigger this action on. Can be any branch name.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DigitalOcean
      run: |
        echo "DIGITALOCEAN_ACCESS_TOKEN=YOUR_TOKEN_HERE" >> $DOORNEXT_SERVER_TOKEN
   
    - name: Checkout to the branch
      uses: actions/checkout@v2
      with:
        ref: ctb-server # The branch to check out. This can be a branch name, tag, or commit SHA.
    - uses: actions/checkout@v2
    - name: Check current branch name
      run: |
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        echo "Current branch: $current_branch"  
    - name: Install the required dependencies and run the server
      run: npm intall
      run: pm2 start server.js
    - name: Checkout to /myty-client directory
      run: cd myty-client
    - name: Install dependencies
      run: npm i
      run: npm run deploy-production
    
